export const uiStrings = {
   "English": {
       startChatting: "Start chatting",
       webcamError: "Could not access the webcam. Please check permissions.",
       capture: "Capture",
       language: "Language",
       personaChat: "Persona Chat",
       appDescription: "Select a situation and language to practice your conversational skills.",
       startSession: "Start Session",
       analyzing: "Analyzing...",
       endAndGetFeedback: "End & Get Feedback",
       goBack: "Go Back",
       goal: "Goal:",
       ratingCriteria: "Rating Criteria",
       green: "Green:",
       yellow: "Yellow:",
       red: "Red:",
       finalFeedback: "Final Feedback",
       practiceAgain: "Practice Again",
       selectSituation: "Select a Situation to Begin",
       getStarted: "Use the panel on the left to get started.",
       whatDoYouSee: "What do you see?",
       errorOccurred: "Sorry, an error occurred.",
       stagedImageAlt: "Staged for sending",
       inputPlaceholder: "Type your message or use the mic...",
       sttTitle: "Speech-to-Text",
       send: "Send",
       userCaptureAlt: "User capture",
       unsupportedBrowser: "Browser doesn't support speech recognition.",
       sendMessageFirst: "Send at least one message to get feedback",
       Professional: "Professional",
       Social: "Social",
       Personal: "Personal",
       Limited: "Limited",
   },
   "Mandarin Chinese": {
       startChatting: "开始聊天",
       webcamError: "无法访问网络摄像头。请检查权限。",
       capture: "捕获",
       language: "语言",
       personaChat: "角色扮演聊天",
       appDescription: "选择一个情景和语言来练习你的会话技巧。",
       startSession: "开始会话",
       analyzing: "分析中...",
       endAndGetFeedback: "结束并获取反馈",
       goBack: "返回",
       goal: "目标：",
       ratingCriteria: "评分标准",
       green: "绿色：",
       yellow: "黄色：",
       red: "红色：",
       finalFeedback: "最终反馈",
       practiceAgain: "再次练习",
       selectSituation: "选择一个情景开始",
       getStarted: "使用左侧面板开始。",
       whatDoYouSee: "你看到了什么？",
       errorOccurred: "抱歉，发生了错误。",
       stagedImageAlt: "准备发送",
       inputPlaceholder: "输入您的消息或使用麦克风...",
       sttTitle: "语音转文字",
       send: "发送",
       userCaptureAlt: "用户捕获",
       unsupportedBrowser: "浏览器不支持语音识别。",
       sendMessageFirst: "请至少发送一条消息以获取反馈",
       Professional: "专业",
       Social: "社交",
       Personal: "个人",
       Limited: "有限",
   },
   "Spanish": {
       startChatting: "Empezar a chatear",
       webcamError: "No se pudo acceder a la cámara web. Por favor, compruebe los permisos.",
       capture: "Capturar",
       language: "Idioma",
       personaChat: "Chat de Persona",
       appDescription: "Seleccione una situación e idioma para practicar sus habilidades de conversación.",
       startSession: "Iniciar Sesión",
       analyzing: "Analizando...",
       endAndGetFeedback: "Finalizar y Obtener Feedback",
       goBack: "Volver",
       goal: "Meta:",
       ratingCriteria: "Criterios de Calificación",
       green: "Verde:",
       yellow: "Amarillo:",
       red: "Rojo:",
       finalFeedback: "Feedback Final",
       practiceAgain: "Practicar de Nuevo",
       selectSituation: "Seleccione una Situación para Empezar",
       getStarted: "Use el panel de la izquierda para empezar.",
       whatDoYouSee: "¿Qué ves?",
       errorOccurred: "Lo sentimos, ha ocurrido un error.",
       stagedImageAlt: "En cola para enviar",
       inputPlaceholder: "Escriba su mensaje o use el micrófono...",
       sttTitle: "Voz a Texto",
       send: "Enviar",
       userCaptureAlt: "Captura de usuario",
       unsupportedBrowser: "El navegador no soporta el reconocimiento de voz.",
       sendMessageFirst: "Envíe al menos un mensaje para obtener retroalimentación",
       Professional: "Profesional",
       Social: "Social",
       Personal: "Personal",
       Limited: "Limitado",
   },
   "Vietnamese": {
       startChatting: "Bắt đầu trò chuyện",
       webcamError: "Không thể truy cập webcam. Vui lòng kiểm tra quyền.",
       capture: "Chụp",
       language: "Ngôn ngữ",
       personaChat: "Trò chuyện Persona",
       appDescription: "Chọn một tình huống và ngôn ngữ để thực hành kỹ năng giao tiếp của bạn.",
       startSession: "Bắt đầu phiên",
       analyzing: "Đang phân tích...",
       endAndGetFeedback: "Kết thúc & Nhận Phản hồi",
       goBack: "Quay lại",
       goal: "Mục tiêu:",
       ratingCriteria: "Tiêu chí Đánh giá",
       green: "Xanh:",
       yellow: "Vàng:",
       red: "Đỏ:",
       finalFeedback: "Phản hồi cuối cùng",
       practiceAgain: "Thực hành lại",
       selectSituation: "Chọn một tình huống để bắt đầu",
       getStarted: "Sử dụng bảng điều khiển bên trái để bắt đầu.",
       whatDoYouSee: "Bạn thấy gì?",
       errorOccurred: "Xin lỗi, đã xảy ra lỗi.",
       stagedImageAlt: "Sẵn sàng để gửi",
       inputPlaceholder: "Nhập tin nhắn của bạn hoặc sử dụng micrô...",
       sttTitle: "Giọng nói thành văn bản",
       send: "Gửi",
       userCaptureAlt: "Người dùng chụp",
       unsupportedBrowser: "Trình duyệt không hỗ trợ nhận dạng giọng nói.",
       sendMessageFirst: "Gửi ít nhất một tin nhắn để nhận phản hồi",
       Professional: "Chuyên nghiệp",
       Social: "Xã hội",
       Personal: "Cá nhân",
       Limited: "Giới hạn",
   },
   "French": {
       startChatting: "Commencer à discuter",
       webcamError: "Impossible d'accéder à la webcam. Veuillez vérifier les autorisations.",
       capture: "Capturer",
       language: "Langue",
       personaChat: "Chat Persona",
       appDescription: "Sélectionnez une situation et une langue pour pratiquer vos compétences conversationnelles.",
       startSession: "Démarrer la session",
       analyzing: "Analyse en cours...",
       endAndGetFeedback: "Terminer et Obtenir un Feedback",
       goBack: "Retour",
       goal: "Objectif :",
       ratingCriteria: "Critères d'Évaluation",
       green: "Vert :",
       yellow: "Jaune :",
       red: "Rouge :",
       finalFeedback: "Feedback Final",
       practiceAgain: "Pratiquer à nouveau",
       selectSituation: "Sélectionnez une situation pour commencer",
       getStarted: "Utilisez le panneau de gauche pour commencer.",
       whatDoYouSee: "Que voyez-vous ?",
       errorOccurred: "Désolé, une erreur est survenue.",
       stagedImageAlt: "Prêt pour l'envoi",
       inputPlaceholder: "Tapez votre message ou utilisez le micro...",
       sttTitle: "Parole en Texte",
       send: "Envoyer",
       userCaptureAlt: "Capture de l'utilisateur",
       unsupportedBrowser: "Le navigateur ne prend pas en charge la reconnaissance vocale.",
       sendMessageFirst: "Envoyez au moins un message pour obtenir des commentaires",
       Professional: "Professionnel",
       Social: "Social",
       Personal: "Personnel",
       Limited: "Limité",
   },
   "Hindi": {
       startChatting: "चैटिंग शुरू करें",
       webcamError: "वेबकैम तक नहीं पहुंच सका। कृपया अनुमतियों की जांच करें।",
       capture: "कैप्चर",
       language: "भाषा",
       personaChat: "पर्सोना चैट",
       appDescription: "अपनी बातचीत कौशल का अभ्यास करने के लिए एक स्थिति और भाषा चुनें।",
       startSession: "सत्र शुरू करें",
       analyzing: "विश्लेषण हो रहा है...",
       endAndGetFeedback: "समाप्त करें और प्रतिक्रिया प्राप्त करें",
       goBack: "वापस जाओ",
       goal: "लक्ष्य:",
       ratingCriteria: "रेटिंग मानदंड",
       green: "हरा:",
       yellow: "पीला:",
       red: "लाल:",
       finalFeedback: "अंतिम प्रतिक्रिया",
       practiceAgain: "फिर से अभ्यास करें",
       selectSituation: "शुरू करने के लिए एक स्थिति चुनें",
       getStarted: "शुरू करने के लिए बाईं ओर के पैनल का उपयोग करें।",
       whatDoYouSee: "आप क्या देखते हैं?",
       errorOccurred: "क्षमा करें, एक त्रुटि हुई।",
       stagedImageAlt: "भेजने के लिए तैयार",
       inputPlaceholder: "अपना संदेश टाइप करें या माइक का उपयोग करें...",
       sttTitle: "वाक् से पाठ",
       send: "भेजें",
       userCaptureAlt: "उपयोगकर्ता कैप्चर",
       unsupportedBrowser: "ब्राउज़र वाक् पहचान का समर्थन नहीं करता है।",
       sendMessageFirst: "प्रतिक्रिया प्राप्त करने के लिए कम से कम एक संदेश भेजें",
       Professional: "पेशेवर",
       Social: "सामाजिक",
       Personal: "व्यक्तिगत",
       Limited: "सीमित",
   }
};
